project:
  type: website
  title: "Felipe Elorrieta"
  output-dir: docs

website:
  title: "Felipe Elorrieta"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: teaching.qmd
        text: "Teaching"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

