project:
  type: website
  title: "Felipe Elorrieta"
  output-dir: docs

website:
  title: "Felipe Elorrieta"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about/index.qmd
        text: "About Me"
      - href: courses/index.qmd
        text: "Teaching"
      - href: research/index.qmd
        text: "My Research"
      - href: gallery/index.qmd
        text: "Gallery"
    right:
      - icon: twitter
        text: twitter
        href: https://twitter.com/felocarril
      - icon: github
        text: Github
        href: https://github.com/felipeelorrieta
      - icon: instagram
        text: instagram
        href: https://www.instagram.com/felocarril
      - icon: linkedin
        aria-label: "LinkedIn"
        href: https://www.linkedin.com/in/felipe-elorrieta-0165a259/
      - icon: envelope
        href: mailto:felipe.elorrieta@usach.cl
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

title-block-banner: "#00000000"
title-block-banner-color: "rgba(255, 255, 255, 0.9)"
include-in-header:
  - text: |
      <style>
      .quarto-title-block .quarto-title-banner {
        flex-direction: row;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 400px;
        z-index: 2;
        padding: 0 ;
        background-image: 
        /* top, transparent red */
            linear-gradient(
                rgba(100, 100, 100, 0.8), 
                rgba(100, 100, 100, 0.8)
                ),
                url(images/AM.png);
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
        }
       .quarto-title-block .quarto-title-banner::before {
        content: '';
        background-image: url(images/Yo2.png);
        background-repeat: no-repeat;
        background-position: center;
        background-size: contain;
        width: 300px;
        height: 300px;
        margin-right: 20px;
      }
      .quarto-title-block .quarto-title-banner h1.title {
        margin: 0;
        text-align: left;
        font-size: 2.5em;
      }
      </style>

