project:
  type: website
  title: "Felipe Elorrieta"
  output-dir: docs

website:
  title: "Felipe Elorrieta"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about/index.qmd
        text: "About Me"
      - href: courses/index.qmd
        text: "Teaching"
      - href: research/index.qmd
        text: "My Research"
      - href: gallery/index.qmd
        text: "Gallery"
      - href: outreach/index.qmd
        text: "Outreach"
    right:
      - icon: twitter
        text: twitter
        href: https://twitter.com/felocarril
      - icon: github
        text: Github
        href: https://github.com/felipeelorrieta
      - icon: instagram
        text: instagram
        href: https://www.instagram.com/felocarril
      - icon: linkedin
        aria-label: "LinkedIn"
        href: https://www.linkedin.com/in/felipe-elorrieta-0165a259/
      - icon: envelope
        href: mailto:felipe.elorrieta@usach.cl
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full


