setwd("/Users/felo/Dropbox/Series de Tiempo/Curso Soche") 
data<-read.table("PARAUCO.SN.csv",header=T,sep=",")
data2<-read.table("MALLPLAZA.SN.csv",header=T,sep=",")
multidata=as.data.frame(cbind(data[,5],data2[,5]))
multidata=na.omit(multidata)
data=as.numeric(multidata[,1])
data2=as.numeric(multidata[,2])
par(mfrow=c(2,1))
ts.plot(data,main="Precio Cierre Parque Arauco",ylab="",xlab="Dia")
ts.plot(data2,main="Precio Cierre Mall Plaza",ylab="",xlab="Dia")
adfTest(data, lags = 1, type = c("nc"))
adfTest(data2, lags = 1, type = c("nc"))

###Engle-Granger procedure

model=lm(data~data2)
adfTest(residuals(model), lags = 1, type = c("nc"))
grangertest(data ~ data2,order=1,multidata)
grangertest(data2 ~ data,order=1,multidata)

par(mfrow=c(2,2))
rtn=diff(log(data))
ts.plot(rtn,main="Retorno Compuesto Continuamente Cierre Parque Arauco",ylab="",xlab="Dia")
rtn2=diff(log(data2))
ts.plot(rtn2,main="Retorno Compuesto Continuamente Cierre Mall Plaza",ylab="",xlab="Dia")
acf(rtn, lwd=3, main ="")
title(expression(paste("ACF ", r["1t"])))
acf(rtn2, lwd=3, main ="")
title(expression(paste("ACF ", r["2t"])))
adfTest(rtn, lags = 1, type = c("nc"))
adfTest(rtn2, lags = 1, type = c("nc"))
grangertest(rtn ~ rtn2,order=1)
grangertest(rtn2 ~ rtn,order=1)
par(mfrow=c(1,1))
ccf(rtn,rtn2,lwd=3,lag.max=10,main="",ylab="CCF") 
title(expression(paste("CCF ", r["1,t+k"]," y ",r["2,t"])))