setwd("/Users/felocarril/Dropbox/Econometría/2-2024/Codigos R")
data<-read.table("PARAUCO.SN.csv",header=T,sep=",")
data2<-read.table("MALLPLAZA.SN.csv",header=T,sep=",")
multidata=as.data.frame(cbind(data[,5],data2[,5]))
multidata=na.omit(multidata)
data=as.numeric(multidata[,1])
data2=as.numeric(multidata[,2])
par(mfrow=c(2,1))
ts.plot(data,main="Precio Cierre Parque Arauco",ylab="",xlab="Dia")
ts.plot(data2,main="Precio Cierre Mall Plaza",ylab="",xlab="Dia")
require(fUnitRoots)
require(lmtest)
adfTest(data, lags = 1, type = c("nc"))
adfTest(data2, lags = 1, type = c("nc"))

###Engle-Granger procedure

model=lm(data~data2)
adfTest(residuals(model), lags = 1, type = c("nc"))
grangertest(data ~ data2,order=1,multidata)
grangertest(data2 ~ data,order=1,multidata)

par(mfrow=c(2,2))
rtn=diff(log(data))
ts.plot(rtn,main="Retorno Compuesto Continuamente Cierre Parque Arauco",ylab="",xlab="Dia")
rtn2=diff(log(data2))
ts.plot(rtn2,main="Retorno Compuesto Continuamente Cierre Mall Plaza",ylab="",xlab="Dia")
acf(rtn, lwd=3, main ="")
title(expression(paste("ACF ", r["1t"])))
acf(rtn2, lwd=3, main ="")
title(expression(paste("ACF ", r["2t"])))
adfTest(rtn, lags = 1, type = c("nc"))
adfTest(rtn2, lags = 1, type = c("nc"))
grangertest(rtn ~ rtn2,order=1)
grangertest(rtn2 ~ rtn,order=1)
par(mfrow=c(1,1))
ccf(rtn,rtn2,lwd=3,lag.max=10,main="",ylab="CCF") 
title(expression(paste("CCF ", r["1,t+k"]," y ",r["2,t"])))
#ccf(rtn2,rtn,lwd=2,lag.max=10)

require(vars)
Y=cbind(rtn,rtn2)
VARselect(Y,type="none")
varmodel=VAR(Y,p=1,type="none")
coef2=varmodel$varresult$rtn2$coefficients
coef=varmodel$varresult$rtn$coefficients
coefmatrix=cbind(coef2,coef)
summary(varmodel)
AIC(varmodel)
varmodel2=VAR(Y,p=2,type="none")
summary(varmodel2)
coef2=varmodel2$varresult$rtn2$coefficients
coef=varmodel2$varresult$rtn$coefficients
coefmatrix2=cbind(coef2,coef)
AIC(varmodel2)
par(mfrow=c(2,3))
acf(residuals(varmodel)[,1],lag.max=20,lwd=2, main ="")
title(expression(paste("ACF Modelo 1:", e["1t"])))
acf(residuals(varmodel)[,2],lag.max=20,lwd=2, main ="")
title(expression(paste("ACF Modelo 1:", e["2t"])))
ccf(residuals(varmodel)[,1],residuals(varmodel)[,2],lag.max=10,main="",ylab="CCF",lwd=2) 
title(expression(paste("CCF Modelo 1:", e["1,t+k"]," y ",e["2,t"])))
acf(residuals(varmodel2)[,1],lag.max=20,lwd=2, main ="")
title(expression(paste("ACF Modelo 2:", e["1t"])))
acf(residuals(varmodel2)[,2],lag.max=20,lwd=2, main ="")
title(expression(paste("ACF Modelo 2:", e["2t"])))
ccf(residuals(varmodel2)[,1],residuals(varmodel2)[,2],lag.max=10,main="",ylab="CCF",lwd=2) 
title(expression(paste("CCF Modelo 2:", e["1,t+k"]," y ",e["2,t"])))
par(mfrow=c(2,2))
Box.Test = function(x, lag = 1, main = "p values for Ljung-Box statistic"){

B<-vector("numeric")
for(i in 1:lag){
B[i]<-Box.test(x, lag = i, type = "Ljung-Box")$p.value
}
A<-matrix(cbind(c(1:lag),B), nrow = lag, ncol = 2, dimnames = list(NULL, c("lag", "p.value")))
plot(A[,1], A[,2], ylim = c(0, 1), 
ylab = "p-value", xlab = "Lag", main = main,lwd=2)
abline(0.05, 0, col = 4, lty = 2,lwd=2)
return(A)
}
Box.Test(residuals(varmodel)[,1],20, main= expression(paste(" valores-p Box Ljung Modelo 1:", e["1t"])))
Box.Test(residuals(varmodel)[,2],20, main= expression(paste(" valores-p Box Ljung Modelo 1:", e["2t"])))
Box.Test(residuals(varmodel2)[,1],20, main= expression(paste(" valores-p Box Ljung Modelo 2:", e["1t"])))
Box.Test(residuals(varmodel2)[,2],20, main= expression(paste(" valores-p Box Ljung Modelo 2:", e["2t"])))